apiVersion: apps/v1
kind: Deployment
metadata:
  name: randword
  labels:
    app: randword
spec:
  selector:
    matchLabels:
      app: randword
  template:
    metadata:
      labels:
        app: randword
    spec:
      containers:
        - name: randword
          image: randword
          resources:
            requests:
              cpu: "10m"
          volumeMounts:
          - name: shared-logs
            mountPath: /home/randword/logs
        - name: sidecar
          image: sidecar
          resources:
            requests:
              cpu: "10m"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/logs
      volumes:
        - name: shared-logs
          emptyDir: {}
